//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ Compatible
// This file is automatically generated by RisohEditor 5.7.4.
// mzimeja_res.rc

#define IDC_LOGF_ENTRY                      310
#define IDC_LOGF_API                        311
#define IDC_LOGF_KEY                        312
#define IDC_DEBF_THREADID                   313
#define IDC_DEBF_GUIDELINE                  314

#define IDD_GENERAL                         100
#define IDD_WORDLIST                        101
#define IDD_CHOOSEDICT                      102
#define IDD_ABOUTIME                        103
#define IDD_DEBUG                           104
#define IDD_ADDWORD                         105

#define IDM_RECONVERT                       40001
#define IDM_ABOUT                           40002
#define IDM_HIRAGANA                        40003
#define IDM_FULL_KATAKANA                   40004
#define IDM_FULL_ASCII                      40005
#define IDM_HALF_KATAKANA                   40006
#define IDM_HALF_ASCII                      40007
#define IDM_CANCEL                          40009
#define IDM_ROMAN_INPUT                     40010
#define IDM_KANA_INPUT                      40011
#define IDM_HIDE                            40012
#define IDM_PROPERTY                        40013
#define IDM_ADD_WORD                        40015
#define IDM_IME_PAD                         40016
#define IDM_STROKES                         40017
#define IDM_RADICALS                        40018

#define IDS_PAREN                           100
#define IDS_SYMBOLS                         101
#define IDS_KEISEN                          102
#define IDS_MATH                            103
#define IDS_SANKAKU                         104
#define IDS_SHIKAKU                         105
#define IDS_ZUKEI                           106
#define IDS_MARU                            107
#define IDS_STARS                           108
#define IDS_HISHI                           109
#define IDS_POINTS                          110
#define IDS_UNITS                           111
#define IDS_FUTOUGOU                        112
#define IDS_TATE                            113
#define IDS_TATE_HIDARI                     114
#define IDS_TATE_MIGI                       115
#define IDS_HIDARI_UE                       116
#define IDS_HIDARI_SHITA                    117
#define IDS_FUTO_WAKU                       118
#define IDS_HOSO_WAKU                       119
#define IDS_MANNAKA                         120
#define IDS_MIGI_UE                         121
#define IDS_MIGI_SHITA                      122
#define IDS_YOKO                            123
#define IDS_YOKO_UE                         124
#define IDS_YOKO_SHITA                      125
#define IDS_SAME                            126
#define IDS_ARROWS                          127
#define IDS_GREEK                           128
#define IDS_UP                              129
#define IDS_DOWN                            130
#define IDS_LEFT                            131
#define IDS_RIGHT                           132
#define IDS_WORD                            133
#define IDS_READING                         134
#define IDS_HINSHI                          135
#define IDS_WANNADELETEWORD                 136
#define IDS_HINSHIWRONG                     137
#define IDS_DICFILENAME                     1000
#define IDS_CONFIGNAME                      1001
#define IDS_GL_NODICTIONARY                 1010
#define IDS_GL_TYPINGERROR                  1011
#define IDS_GL_TESTGUIDELINESTR             1012
#define IDS_GL_TESTGUIDELINEPRIVATE         1013
#define IDS_NOREADING                       1020
#define IDS_NOSTRING                        1021
#define IDS_NOMEMORY                        1022
#define IDS_REGWORDRET                      1023
#define IDS_IMENAME                         1024
#define IDS_RECONVERT                       40001
#define IDS_VERSIONINFO                     40002
#define IDS_HIRAGANA                        40003
#define IDS_ZENKAKU_KATAKANA                40004
#define IDS_ZENKAKU_EISUU                   40005
#define IDS_HANKAKU_KANA                    40006
#define IDS_HANKAKU_EISUU                   40007
#define IDS_CANCEL                          40009
#define IDS_ROMAJI_INPUT                    40010
#define IDS_KANA_INPUT                      40011
#define IDS_PROPERTY                        40013
#define IDS_REGISTERWORD                    40015
#define IDS_IMEPAD                          40016
#define IDS_HINSHI_00                       40017
#define IDS_HINSHI_01                       40018
#define IDS_HINSHI_02                       40019
#define IDS_HINSHI_03                       40020
#define IDS_HINSHI_04                       40021
#define IDS_HINSHI_05                       40022
#define IDS_HINSHI_06                       40023
#define IDS_HINSHI_07                       40024
#define IDS_HINSHI_08                       40025
#define IDS_HINSHI_09                       40026
#define IDS_HINSHI_10                       40027
#define IDS_HINSHI_11                       40028
#define IDS_HINSHI_12                       40029
#define IDS_HINSHI_13                       40030
#define IDS_HINSHI_14                       40031
#define IDS_HINSHI_15                       40032
#define IDS_HINSHI_16                       40033
#define IDS_HINSHI_17                       40034
#define IDS_HINSHI_18                       40035
#define IDS_HINSHI_19                       40036
#define IDS_HINSHI_20                       40037
#define IDS_HINSHI_21                       40038
#define IDS_HINSHI_22                       40039
#define IDS_HINSHI_23                       40040
#define IDS_HINSHI_24                       40041
#define IDS_HINSHI_25                       40042
#define IDS_HINSHI_26                       40043

#ifdef APSTUDIO_INVOKED
    #ifndef APSTUDIO_READONLY_SYMBOLS
        #define _APS_NO_MFC                 1
        #define _APS_NEXT_RESOURCE_VALUE    100
        #define _APS_NEXT_COMMAND_VALUE     40019
        #define _APS_NEXT_CONTROL_VALUE     1000
        #define _APS_NEXT_SYMED_VALUE       300
    #endif
#endif
