//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ Compatible
// This file is automatically generated by RisohEditor.
// mzimeja_res.rc

#define DLG_GENERAL                         100
#define DLG_REGISTERWORD                    101
#define DLG_SELECTDICTIONARY                102
#define DLG_ABOUT                           103
#define DLG_DEBUG                           104

#define IDC_LOGF_ENTRY                      310
#define IDC_LOGF_API                        311
#define IDC_LOGF_KEY                        312
#define IDC_DEBF_THREADID                   313
#define IDC_DEBF_GUIDELINE                  314

#define IDM_RECONVERT                       40001
#define IDM_ABOUT                           40002
#define IDM_HIRAGANA                        40003
#define IDM_FULL_KATAKANA                   40004
#define IDM_FULL_ASCII                      40005
#define IDM_HALF_KATAKANA                   40006
#define IDM_HALF_ASCII                      40007
#define IDM_CANCEL                          40009
#define IDM_ROMAN_INPUT                     40010
#define IDM_KANA_INPUT                      40011
#define IDM_HIDE                            40012
#define IDM_PROPERTY                        40013
#define IDM_ADD_WORD                        40015
#define IDM_IME_PAD                         40016
#define IDM_STROKES                         40017
#define IDM_RADICALS                        40018

#define IDS_DICFILENAME                     1000
#define IDS_CONFIGNAME                      1001
#define IDS_GL_NODICTIONARY                 1010
#define IDS_GL_TYPINGERROR                  1011
#define IDS_GL_TESTGUIDELINESTR             1012
#define IDS_GL_TESTGUIDELINEPRIVATE         1013
#define IDS_NOREADING                       1020
#define IDS_NOSTRING                        1021
#define IDS_NOMEMORY                        1022
#define IDS_REGWORDRET                      1023

#define ID_WR_READING                       200
#define ID_WR_STRING                        201
#define ID_WR_STYLE                         202
#define ID_SD_SELDIC                        301
#define ID_SD_DICPATH                       302

#define VER_DEBUG                           0

#ifdef APSTUDIO_INVOKED
    #ifndef APSTUDIO_READONLY_SYMBOLS
        #define _APS_NO_MFC                 1
        #define _APS_NEXT_RESOURCE_VALUE    100
        #define _APS_NEXT_COMMAND_VALUE     40019
        #define _APS_NEXT_CONTROL_VALUE     1000
        #define _APS_NEXT_SYMED_VALUE       300
    #endif
#endif
