//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ Compatible
// This file is automatically generated by RisohEditor 5.8.7.
// ime_setup_res.rc

#define IDS_APPNAME                         1
#define IDS_REGFAILED                       2
#define IDS_FAILCOPYFILE                    3
#define IDS_IMELAYOUTTEXT                   4
#define IDS_FAILDOCONTACT                   5
#define IDS_REGDELETEFAIL                   6
#define IDS_FAILDELETEFILE                  7
#define IDS_REGSETUPFAIL                    8
#define IDS_SETUPOK                         9
#define IDS_SETUPFAIL                       10

#ifdef APSTUDIO_INVOKED
    #ifndef APSTUDIO_READONLY_SYMBOLS
        #define _APS_NO_MFC                 1
        #define _APS_NEXT_RESOURCE_VALUE    100
        #define _APS_NEXT_COMMAND_VALUE     100
        #define _APS_NEXT_CONTROL_VALUE     1000
        #define _APS_NEXT_SYMED_VALUE       300
    #endif
#endif
